// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WPTServiciosDGII.Data;

#nullable disable

namespace WPTServiciosDGII.Migrations
{
    [DbContext(typeof(WptDbContext))]
    [Migration("20260410145152_InitialApiCreate")]
    partial class InitialApiCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WPTServiciosDGII.Models.DocumentoRecibido", b =>
                {
                    b.Property<int>("DocumentoRecibidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentoRecibidoId"));

                    b.Property<string>("DocumentoRecibidoEstado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DocumentoRecibidoFecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentoRecibidoMensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DocumentoRecibidoNCF")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DocumentoRecibidoRncEmisor")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DocumentoRecibidoRncReceptor")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DocumentoRecibidoTipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DocumentoRecibidoTrackId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DocumentoRecibidoXML")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NucleoID")
                        .HasColumnType("int");

                    b.HasKey("DocumentoRecibidoId");

                    b.HasIndex("DocumentoRecibidoNCF");

                    b.HasIndex("DocumentoRecibidoTrackId");

                    b.ToTable("Api_DocumentoRecibido");
                });

            modelBuilder.Entity("WPTServiciosDGII.Models.LogInteraccion", b =>
                {
                    b.Property<int>("LogInteraccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogInteraccionId"));

                    b.Property<string>("LogInteraccionEndpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LogInteraccionEstado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("LogInteraccionFecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogInteraccionIpOrigen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LogInteraccionMetodo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("LogInteraccionMsRespuesta")
                        .HasColumnType("int");

                    b.Property<string>("LogInteraccionRequestBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogInteraccionResponseBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogInteraccionRnc")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("LogInteraccionServicio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LogInteraccionTokenId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LogInteraccionId");

                    b.HasIndex("LogInteraccionFecha");

                    b.HasIndex("LogInteraccionServicio");

                    b.ToTable("Api_LogInteraccion");
                });

            modelBuilder.Entity("WPTServiciosDGII.Models.SemillaGenerada", b =>
                {
                    b.Property<int>("SemillaGeneradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemillaGeneradaId"));

                    b.Property<DateTime>("SemillaGeneradaFecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("SemillaGeneradaRnc")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("SemillaGeneradaUsada")
                        .HasColumnType("bit");

                    b.Property<string>("SemillaGeneradaValor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SemillaGeneradaId");

                    b.HasIndex("SemillaGeneradaValor")
                        .IsUnique();

                    b.ToTable("Api_SemillaGenerada");
                });

            modelBuilder.Entity("WPTServiciosDGII.Models.TokenEmitido", b =>
                {
                    b.Property<int>("TokenEmitidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenEmitidoId"));

                    b.Property<bool>("TokenEmitidoActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TokenEmitidoFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TokenEmitidoFechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenEmitidoRnc")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TokenEmitidoValor")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("TokenEmitidoId");

                    b.HasIndex("TokenEmitidoValor");

                    b.HasIndex("TokenEmitidoActivo", "TokenEmitidoFechaExpiracion");

                    b.ToTable("Api_TokenEmitido");
                });
#pragma warning restore 612, 618
        }
    }
}
